#
# Makefile for the Linux ZFS filesystem routines.
#

obj-$(CONFIG_ZFS_FS) += zfs.o
zfs-objs := chardev.o data-coding.o dir.o file.o inode.o super.o zfs_prot.o zfsd_call.o

# If you want debugging output, please uncomment the following line.

# EXTRA_CFLAGS += -DDEBUG
